running_shopping/carttest/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views, view_order

urlpatterns = [
    # 购物车
    url(r'^$', views.cart, name='cart'),
    # 添加商品
    url(r'addcart(\d+)_(\d+)/$', views.addcart, name='addcart'),
    # 输出用户所以商品
    url(r'^item/$', views.item),
    # 增加或减少商品数量
    url(r'^alter(\d+)_(\d+)/$', views.alter),
    # blur 输入数据错误
    url(r'^error(\d+)/$', views.error),
    # 删除购物车数据
    url(r'^delete_item(\d+)/$', views.delete_item),
    # 获取用户购物车数量
    url(r'^goods_count/$', views.goods_count),

]

running_shopping/running_shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('goodstest.urls', namespace='goodstest')),
    url(r'^user/', include('usertest.urls', namespace='usertest')),
    url(r'^cart/', include('carttest.urls', namespace='carttest')),
    url(r'^order/',include('ordertest.urls',namespace='ordertest'))
]

running_shopping/usertest/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url

from . import views, view_order

urlpatterns = [
    url(r'^login/$', views.login, name='login'),  # 用户登录
    url(r'^login_hander/$', views.login_hander),  # 处理登录
    url(r'^logout/$', views.logout, name='logout'),  # 注销
    url(r'^register/$', views.register, name='register'),  # 注册
    url(r'^base/$', views.base),
    url(r'^register_hander/$', views.register_hander),  # 注册处理
    url(r'^user_exist/$', views.user_exist),

    url(r'^info/$', view_order.info, name='info'),  # 用户中心
    url(r'^order/$', view_order.order, name='order'),  # 用户订单

    url(r'^ordersubmit/$', view_order.ordersubmit),  # 提交订单
    # url(r'^ordersubmit2/$',view_order.ordersubmit2),
    url(r'^site/$', view_order.site, name='site'),  # 收货地址
    url(r'^site_hander/$', view_order.site_hander),  # 处理收货地址
    url(r'^site_modify/$', view_order.site_modify),  # 修还收货地址
    url(r'^address([0-9]+)/$', view_order.useraddress),  # 获取地址信息
    url(r'^set_default([0-9]+)/$', view_order.set_default),  # 设置默认地址

    # 添加评价
    url(r'^addcomment/$', view_order.addcomment),
    url(r'^save_comment/$', view_order.save_comment),
    # 删除订单
    url(r'^delete_order/$', view_order.delete_order),
    # #获取同级下的城市信息
    # url(r'^city([0-9]+)/$',view_order.city()),

    # 三级联动
    # url(r'^index2/$', view_order.index2, name='index2'),
    url(r'^pro/$', view_order.getarea1, name='prolist'),
    url(r'^(?P<pid>\d+)/$', view_order.getarea2),

]

running_shopping/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	{% block meta %}
	{% endblock meta %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-{{ title|default:'用户中心' }}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/main.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/detail.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/main.ie6.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/main.ie7.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/my.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/lipin.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/lr.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/info.css">
	<link rel="stylesheet" type="text/css" href="/static/css2/list.css">

	
	
	
	
	
	
	
	
	
	<script type="text/javascript" src="/static/js/jquery-1.8.3.js"></script>
	<script type="text/javascript">
		$.get('/cart/goods_count/',function(dic){
			$('#show_count').text(dic.count)
		})
	</script>
    {% block base_script %}
    {% endblock base_script %}
</head>
<body>
{% block base_top %}

	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                <div class="login_btn fl">
					<a href="/">首页</a>
					<span>|</span>
				</div>
                {% if request.session.uname|default:'' != '' %}
                <div class="login_btn fl">
					<a href="{% url 'usertest:info' %}">账号：{{ request.session.uname }}</a>
					<span>|</span>
					<a href="{% url 'usertest:logout' %}">注销</a>
				</div>
                {% else %}

				<div class="login_btn fl">
					<a href="{% url 'usertest:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'usertest:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'usertest:info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'carttest:cart' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'usertest:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>

{% endblock base_top %}
{% block base_body %}
{% endblock base_body %}

{% block base_bottom %}

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2018 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{% endblock base_bottom %}
</body>
</html>

running_shopping/templates/base_bottom.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-{{title}}</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
    {% block script %}
    {% endblock script %}
</head>
<body>
	{% block body %}
	{% endblock body %}

    {% block bottom %}
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
	 {% endblock bottom %}
</body>
</html>

running_shopping/templates/base_goods.html
{% extends 'base.html' %}
{% block base_script %}

<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>
<script type="text/javascript" src="/static/js/slide.js"></script>

{% block goods_script %}

{% endblock goods_script %}
{% endblock base_script %}
{% block base_body %}


<div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="search_con fl">
        <form method="get" action="/search/" target="_blank">
            <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
            <input type="submit" class="input_btn fr" name="" value="搜索">
        </form>
    </div>
    <div class="guest_cart fr">
        <a href="/cart" class="cart_name fl">我的购物车</a>
        <div class="goods_count fl" id="show_count"></div>
    </div>
</div>
{% block user_menu %}
<div class="navbar_con">
    <div class="navbar clearfix">
        <div class="subnav_con fl">
            <h1>全部商品分类</h1>
            <span></span>
            <ul class="subnav">
                <li><a href="/list_1" class="fruit">新鲜水果</a></li>
                <li><a href="/list_2" class="seafood">海鲜水产</a></li>
                <li><a href="/list_3" class="meet">猪牛羊肉</a></li>
                <li><a href="/list_4" class="egg">禽类蛋品</a></li>
                <li><a href="/list_5" class="vegetables">新鲜蔬菜</a></li>
                <li><a href="/list_6" class="ice">速冻食品</a></li>
            </ul>
        </div>
        <ul class="navlist fl">
            <li><a href="/">首页</a></li>
            <li class="interval">|</li>
            <li><a href="">手机生鲜</a></li>
            <li class="interval">|</li>
            <li><a href="">抽奖</a></li>
        </ul>
    </div>
</div>

{% endblock user_menu %}
{% block user_body %}
{% endblock user_body %}
{% endblock base_body %}

running_shopping/templates/base_user.html
{% extends 'base.html' %}

{% block base_body %}

{% block user_search %}

<div class="search_bar clearfix">
    <a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title|default:'用户中心' }}</div>
    <div class="search_con fr">
        <form method="get" action="/search/">
            <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
            <input type="submit" class="input_btn fr" name="" value="搜索">
        </form>
    </div>
</div>
{% endblock user_search %}
{% block user_body %}

<div class="main_con clearfix">
    {% block user_left %}

    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'usertest:info' %}">· 个人信息</a></li>
            <li><a href="{% url 'usertest:order' %}" class="active">· 全部订单</a></li>
            <li><a href="{% url 'usertest:site' %}">· 收货地址</a></li>
        </ul>
    </div>
    {% endblock user_left %}
    {% block user_right %}
    {% endblock user_right %}
</div>
{% endblock user_body %}
{% endblock base_body %}

running_shopping/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <div>
        <form>
            <img src="/static/images/goods/goods001.jpg" >
            <textarea></textarea>
        </form>
    </div>
</head>
<body>

</body>
</html>