running_shopping/carttest/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views, view_order

urlpatterns = [
    # 购物车
    url(r'^$', views.cart, name='cart'),
    # 添加商品
    url(r'addcart(\d+)_(\d+)/$', views.addcart, name='addcart'),
    # 输出用户所以商品
    url(r'^item/$', views.item),
    # 增加或减少商品数量
    url(r'^alter(\d+)_(\d+)/$', views.alter),
    # blur 输入数据错误
    url(r'^error(\d+)/$', views.error),
    # 删除购物车数据
    url(r'^delete_item(\d+)/$', views.delete_item),
    # 获取用户购物车数量
    url(r'^goods_count/$', views.goods_count),

]

running_shopping/running_shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('goodstest.urls', namespace='goodstest')),
    url(r'^user/', include('usertest.urls', namespace='usertest')),
    url(r'^cart/', include('carttest.urls', namespace='carttest')),
    url(r'^order/',include('ordertest.urls',namespace='ordertest'))
]

running_shopping/usertest/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url

from . import views, view_order

urlpatterns = [
    url(r'^login/$', views.login, name='login'),  # 用户登录
    url(r'^login_hander/$', views.login_hander),  # 处理登录
    url(r'^logout/$', views.logout, name='logout'),  # 注销
    url(r'^register/$', views.register, name='register'),  # 注册
    url(r'^base/$', views.base),
    url(r'^register_hander/$', views.register_hander),  # 注册处理
    url(r'^user_exist/$', views.user_exist),

    url(r'^info/$', view_order.info, name='info'),  # 用户中心
    url(r'^order/$', view_order.order, name='order'),  # 用户订单

    url(r'^ordersubmit/$', view_order.ordersubmit),  # 提交订单
    # url(r'^ordersubmit2/$',view_order.ordersubmit2),
    url(r'^site/$', view_order.site, name='site'),  # 收货地址
    url(r'^site_hander/$', view_order.site_hander),  # 处理收货地址
    url(r'^site_modify/$', view_order.site_modify),  # 修还收货地址
    url(r'^address([0-9]+)/$', view_order.useraddress),  # 获取地址信息
    url(r'^set_default([0-9]+)/$', view_order.set_default),  # 设置默认地址

    # 添加评价
    url(r'^addcomment/$', view_order.addcomment),
    url(r'^save_comment/$', view_order.save_comment),
    # 删除订单
    url(r'^delete_order/$', view_order.delete_order),
    # #获取同级下的城市信息
    # url(r'^city([0-9]+)/$',view_order.city()),

    # 三级联动
    # url(r'^index2/$', view_order.index2, name='index2'),
    url(r'^pro/$', view_order.getarea1, name='prolist'),
    url(r'^(?P<pid>\d+)/$', view_order.getarea2),

]

running_shopping/ordertest/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# class OrderDetailManagerInfo(models.Manager):
#     def create_orderdetail(self,goods,money,order):
#         detail=self.create(goods_id=goods,money=money,order_id=order)
#         return detail


# 订单
class OrderInfo(models.Model):
    oid = models.CharField(primary_key=True, max_length=20)  # 订单编号,主键
    odate = models.DateTimeField(auto_now=True)  # 创建日期
    statu = models.IntegerField()  # 订单状态
    omoney = models.DecimalField(max_digits=8, decimal_places=2, default=0)  # 订单总价
    oaddress = models.ForeignKey('usertest.UserAddressInfo')  # 收货地址
    ouser = models.ForeignKey('usertest.UserInfo')  # 订单用户

    class Meta():
        db_table = 'orderinfo'

    # def __str__(self):
    #     return self.pk.encode('utf-8')

    def str_statu(self):
        if self.statu == 0:
            return u'未支付'
        elif self.statu == 1:
            return u'已支付'
        elif self.statu == 2:
            return u'已收货'
        else:
            return u'已评价'
    # ststu_str.short_description('')


# 订单详情
class OrderDetailInfo(models.Model):
    goods = models.ForeignKey('goodstest.GoodsInfo', default=0)  # 商品
    money = models.DecimalField(max_digits=8, decimal_places=2)  # 单件
    count = models.IntegerField()  # 商品数量
    order = models.ForeignKey(OrderInfo)  # 订单编号

    # def __str__(self):
    #     return self.pk.encode('utf-8')
    # orderdetail=OrderDetailManagerInfo()
    class Meta():
        db_table = 'orderdetailinfo'

running_shopping/usertest/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# 创建用户
class UserInfoManager(models.Manager):
    def create_user(self, name, pwd, mail):
        user = self.create(uname=name, upwd=pwd, umail=mail)
        return user


# 创建用户收货地址
class UserAddressInfoManager(models.Manager):
    def create_useraddress(self, another_name, recipients, pro, city, disc, address, postcode, addphone, user):
        useraddress = self.create(another_name=another_name, urecipients=recipients, upro=pro,
                                  ucity=city, udisc=disc, uaddress=address,
                                  upostcode=postcode, uaddphone=addphone, userid_id=user)
        return useraddress


# 用户类
class UserInfo(models.Model):
    uname = models.CharField(max_length=20)  # 用户姓名
    upwd = models.CharField(max_length=40)  # 用户密码
    # ugender = models.BooleanField()

    umail = models.CharField(max_length=30)  # 用户邮箱
    goodsids = models.CommaSeparatedIntegerField(default='', max_length=40)  # 用户最经浏览商品id
    default_id = models.IntegerField(default=0)  # 收货地址id
    isDelete = models.BooleanField(default=0)  # 逻辑删除
    user = models.Manager()
    muser = UserInfoManager()

    # 指定编码格式，防止中文乱码
    def __str__(self):
        return self.uname.encode('utf-8')

    # 修改表名
    class Meta():
        db_table = 'userinfo'

    # def gender(self):
    #     if self.ugender:
    #         return '男'
    #     else:
    #         return '女'
    #
    # gender.short_description = 'sex'


# 用户地址类
class UserAddressInfo(models.Model):
    another_name = models.CharField(max_length=20)  # 别名
    urecipients = models.CharField(max_length=20)  # 收件人
    upro = models.IntegerField(default=0)  # 省份id
    ucity = models.IntegerField(default=0)  # 市id
    udisc = models.IntegerField(default=0)  # 区、镇id
    uaddress = models.CharField(max_length=80)  # 街道信息
    upostcode = models.CharField(max_length=6)  # 邮政编码
    uaddphone = models.CharField(max_length=20)  # 用户手机号
    userid = models.ForeignKey('UserInfo')  # 用户id

    useraddress = models.Manager()
    museraddress = UserAddressInfoManager()

    # 指定编码格式，防止中文乱码
    def __str__(self):
        return self.urecipients.encode('utf-8')

    # 修改表名
    class Meta():
        db_table = 'useraddressinfo'


# 区域表 自关联
class AreaInfo(models.Model):
    atitle = models.CharField(max_length=30)  # 区域名称
    aParea = models.ForeignKey('self', null=True, blank=True)  # 外键

    # 指定编码格式，防止中文乱码
    def __str__(self):
        return '%s' % self.atitle

    # 修改表名
    class Meta():
        db_table = 'areainfo'

running_shopping/usertest/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import hashlib
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.http import JsonResponse, HttpResponseRedirect, HttpResponse
from models import UserInfo


def base(request):
    return render(request, 'base_bottom.html')


def login(request):
    uname = request.COOKIES.get('uname', '')
    upwd = request.COOKIES.get('upwd', '')
    name_error = request.COOKIES.get('name_error', 0)
    pwd_error = request.COOKIES.get('pwd_error', 0)
    print '====================', uname, 'a', upwd, 'f', name_error, 'f', pwd_error
    context = {'title': '登录', 'uname': uname, 'upwd': upwd, 'name_error': name_error, 'pwd_error': pwd_error, }
    return render(request, 'usertest/login.html', context)


def login_hander(request):
    # 获取表单提交的信息
    name = request.POST.get('username')
    pwd = request.POST.get('pwd')
    remember = request.POST.get('remember')
    # print 'name', name, 'pwd', pwd

    # 对用户提交的密码，加密
    shal = hashlib.sha1(pwd)
    password = shal.hexdigest()
    # 取出用户信息
    userdata = UserInfo.user.filter(uname=name)
    response = HttpResponseRedirect('/user/login')
    # 判断用户是否是从其他页面重定向到登录页面
    url = request.COOKIES.get('url')
    # pathurl=request.get_full_path()
    # print pathurl,'=========='
    # 若没有，则登录后调转的用户中心
    if not url:
        url = '/user/info'
    # print '****************888888888888', url
    response2 = HttpResponseRedirect(url)
    if userdata:
        name_error = 0

        if password == userdata[0].upwd:
            pwd_error = 0
        else:
            pwd_error = 1
    else:
        name_error = 1
        pwd_error = 1
    response.set_cookie('name_error', name_error)
    response.set_cookie('pwd_error', pwd_error)
    # print '******************', name_error, pwd_error
    if remember == '1':
        print '记录cookie'
        response.set_cookie('uname', name)
        response.set_cookie('upwd', pwd)
        response2.set_cookie('uname', name)
        response2.set_cookie('upwd', pwd)
    else:
        print '删除cookie'
        response.set_cookie('uname', '', max_age=-1)
        response.set_cookie('upwd', '', max_age=-1)
        response2.set_cookie('uname', '', max_age=-1)
        response2.set_cookie('upwd', '', max_age=-1)
    # context = {'title': '登录', 'name_error': name_error, 'pwd_error': pwd_error, 'uname': name, 'upwd': password}
    if name_error == 0 and pwd_error == 0:
        request.session['pid'] = userdata[0].pk
        request.session['uname'] = name
        # 处理最近浏览，
        # 取出用户表存储的最近浏览信息
        user = UserInfo.user.get(pk=userdata[0].pk)
        goodsids = user.goodsids
        goodsid_list = goodsids.split(',')
        try:
            goodsid_list.remove('')
        except Exception as e:
            pass
        # 获取用户登录前，浏览的商品信息
        session_list = request.session.get('id_list', [])
        if len(session_list):
            for i in goodsid_list:
                if i not in session_list:
                    session_list.append(i)
            goodsid_list = session_list
            request.session['id_list'] = []
        if len(goodsid_list) > 5:
            goodsid_list = goodsid_list[0:5]
        # 用户表 和 session 中的信息合并
        ids = ''
        for index in goodsid_list:
            ids = ids + str(index) + ','
        ids = ids[:-1]
        user.goodsids = ids
        user.save()

        return response2
    else:
        return response
        # return redirect('usertest:login',context)


# 用户注销
def logout(request):
    request.session.flush()

    return HttpResponseRedirect('/')


def register(request):
    return render(request, 'usertest/register.html', {'title': '注册'})


def register_hander(request):
    name = request.POST.get('user_name')
    pwd = request.POST.get('pwd')
    email = request.POST.get('email')
    shal = hashlib.sha1(pwd)
    password = shal.hexdigest()
    print password
    UserInfo.muser.create_user(name, password, email)
    return redirect('usertest:login')


# 判断用户是否存在
def user_exist(request):
    name = request.GET.get('name')
    print name
    count = UserInfo.user.filter(uname=name).count()
    print count
    return JsonResponse({'count': count})

running_shopping/templates/usertest/user_center_info.html
{% extends 'base_user.html' %}
{% block base_script %}
<script type="text/javascript" src="/static/js/jquery-1.8.3.js"></script>
<script type="text/javascript" src='/static/js/list.js'></script>


{% endblock base_script %}



{% block user_left %}

<div class="left_menu_con clearfix">
    <h3>用户中心</h3>
    <ul>
        <li><a href="{% url 'usertest:info' %}" class="active">· 个人信息</a></li>
        <li><a href="{% url 'usertest:order' %}">· 全部订单</a></li>
        <li><a href="{% url 'usertest:site' %}">· 收货地址</a></li>
    </ul>
</div>
{% endblock user_left %}

{% block user_right %}


<div class="right_content clearfix">
    {% load cache %}
    {% cache 120 address %}
    <div class="info_con clearfix">
        <h3 class="common_title2">基本信息</h3>

            <table class="user_info_list" >
                <tr>
                    <td><span>账号：</span>{{ user.uname }}</td>
                    <td width="60%"><span>收件名：</span>{{ addressinfo.urecipients }}</td>
                </tr>
                <tr>
                    <td><span>邮箱：</span>{{ user.umail }}</td>
                    <td><span>手机号码：</span>{{ addressinfo.uaddphone }}</td>
                </tr>
                <tr>
                    <td><span>邮编：</span>{{ addressinfo.upostcode }}</td>
                    <td><span>收货地址：</span>{{ address }}</td>
                </tr>
            </table>

    </div>
    {% endcache %}
    <h3 class="common_title2">最近浏览</h3>
    <div class="has_view_list">
        <ul class="goods_type_list clearfix">

            {% for item in goods_list %}

            <li>
                <a href="/detail_{{ item.pk }}"><img src="/static/media/{{ item.gimage }}"></a>
                <h4><a href="/detail_{{ item.pk }}">{{ item.gtitle }}</a></h4>
                <div class="operate">
                    <span class="prize">￥{{ item.gprice }}</span>
                    <span class="unit">{{ item.gprice }}/{{ item.gweight }}</span>
                    <a href="{% url 'carttest:addcart' item.pk 1 %}"  class="add_goods" title="加入购物车"></a>
                </div>
            </li>
            {% endfor %}

        </ul>
    </div>
</div>


{% endblock user_right %}

running_shopping/templates/usertest/user_center_order.html
{% extends 'base_user.html' %}
{% block meta %}
<meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock meta %}
{% block base_script %}
<link href="/static/css/bootstrap.min.css" rel="stylesheet">

<script src="/static/js/jquery-1.11.0.min.js"></script>

<script src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/static/js/userorder.js"></script>
<script src="/static/js/jquery.validate.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/static/js/messages_zh.js" type="text/javascript" charset="utf-8"></script>
<script src="http://static.runoob.com/assets/jquery-validation-1.14.0/lib/jquery.js"></script>
<script src="http://static.runoob.com/assets/jquery-validation-1.14.0/dist/jquery.validate.min.js"></script>
<script src="http://static.runoob.com/assets/jquery-validation-1.14.0/dist/additional-methods.js"></script>
<script src="http://static.runoob.com/assets/jquery-validation-1.14.0/dist/localization/messages_zh.js"></script>


{% endblock base_script %}
{% block user_left %}

<div class="left_menu_con clearfix">
    <h3>用户中心</h3>
    <ul>
        <li><a href="{% url 'usertest:info' %}">· 个人信息</a></li>
        <li><a href="{% url 'usertest:order' %}" class="active">· 全部订单</a></li>
        <li><a href="{% url 'usertest:site' %}">· 收货地址</a></li>
    </ul>
</div>
{% endblock user_left %}


{% block user_right %}


<div class="right_content clearfix">
    <h3 class="common_title2">全部订单</h3>
    <div class="sort_bar">
        {% for item in sort_bar %}
        {% if statu == item.id %}
        <a href="/user/order?statu={{ item.id }}" class="active">{{ item.name }} </a>
        {% else %}
        <a href="/user/order?statu={{ item.id }}">{{ item.name }}</a>
        {% endif %}
        {% endfor %}
    </div>
    {% for item in page.object_list %}

    <ul class="order_list_th w978 clearfix">
        <li class="col01">{{ item.odate }}</li>
        <li class="col02">订单号：{{ item.oid }}</li>
        <li class="col03">地址：{{ address_list.pop }}</li>
        <li class="col04 stress">&nbsp;&nbsp;&nbsp;{{ item.str_statu }}</li>
    </ul>

    <table class="order_list_table w980">
        <tbody>
        <tr>
            <td width="55%">
                {% for each in item.orderdetailinfo_set.all %}

                <ul class="order_goods_list clearfix">
                    <li class="col01"><a href="/detail_{{ each.goods.pk }}"><img  src="/static/media/{{ each.goods.gimage }}"></a></li>
                    <li class="col02">{{ each.goods.gtitle }}<em>{{ each.goods.gprice }}元/{{ each.goods.gweight }}</em>
                    </li>
                    <li class="col03">{{ each.count }}</li>
                    <li class="col04">{{ each.money }}元</li>
                </ul>
                {% endfor %}

            </td>
            <td width="15%">{{ item.omoney }}元</td>

            {% if item.statu == 0 %}
            <td width="15%">待付款</td>
            <td width="15%"><a id="submit" href="" onclick=" submit({{ item.oid }});" class="oper_btn">去付款</a></td>
            {% else %}
            {% if item.statu == 1 %}
            <td width="15%">已付款</td>
            <td width="15%"><a href="#" onclick=" submit({{ item.oid }});" class="oper_btn">确认收货</a></td>
            {% else %}
            {% if item.statu == 2 %}

            <td width="15%">已收货</td>
            <td width="15%"><a data-toggle="modal" data-target="#addcomment" class="oper_btn"
                               onclick="comment_textarea({{ item.oid }})">请添加评论</a></td>
            {% else %}

            <td width="15%">已评价</td>
            <td width="15%"><a class="oper_btn" onclick="delete_order({{ item.oid }})">删除订单</a></td>
            {% endif %}
            {% endif %}

            {% endif %}
        </tr>
        </tbody>
    </table>
    {% endfor %}

    {% if page.object_list %}

    <div class="pagenation">
        {% if page.has_previous %}
            <a href="/user/order?pag={{ page.previous_page_number }}&amp;statu={{ statu }}">上一页</a>
        {% else %}
             <a href="#" class="active2">上一页</a>
        {% endif %}


        {% if paginator.num_pages < 7 %}

            {% for index in paginator.page_range %}
                {% if index == page.number %}
                    <a href="#" class="active">{{ index }}</a>
                {% else %}
                     <a href="/user/order?pag={{ index }}&amp;statu={{ statu }}">{{ index }}</a>
                {% endif %}
            {% endfor %}
        {% else %}

            {% if page.number < 6 %}
                {% for index in range_page %}
                    {% if index == page.number %}
                         <a href="#" class="active">{{ index }}</a>
                    {% else %}
                         <a href="/user/order?pag={{ index }}&amp;statu={{ statu }}">{{ index }}</a>
                    {% endif %}
                {% endfor %}
                    <a href="#" class="active2">...</a>
                    <a href="/user/order?pag={{ paginator.num_pages }}&amp;statu={{ statu }}">{{ paginator.num_pages }}</a>
            {% else%}
                {% if page.number < pagenum %}

                    <a href="/user/order?pag=1&amp;statu={{ statu }}">1</a>
                    <a href="/user/order?pag=2&amp;statu={{ statu }}">2</a>
                    <a href="#" class="active2">...</a>
                    {% for index in range_page2 %}
                        {% if index == page.number %}
                             <a href="#" class="active">{{ index }}</a>
                        {% else %}
                             <a href="/user/order?pag={{ index }}&amp;statu={{ statu }}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}
                            <a href="#" class="active">...</a>
                            <a href="/user/order?pag={{ paginator.num_pages }}&amp;statu={{ statu }}">{{ paginator.num_pages }}</a>

                {% else %}
                    <a href="/user/order?pag=1&amp;statu={{ statu }}">1</a>
                    <a href="/user/order?pag=2&amp;statu={{ statu }}">2</a>
                    <a href="#" class="active2&amp;statu={{ statu }}">...</a>

                    {% for index in range_page2 %}
                        {% if index == page.number %}
                             <a href="#" class="active">{{ index }}</a>
                        {% else %}
                             <a href="/user/order?pag={{ index }}&amp;statu={{ statu }}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}

                {% endif %}

            {% endif %}

        {% endif %}


        {% if page.has_next %}
        <a href="/user/order?pag={{ page.next_page_number }}&amp;statu={{ statu }}">下一页</a>
        {% else %}
        <a href="#" class="active2">下一页</a>
        {% endif %}
    </div>
    {% else %}
    <table width="60%" style="margin:100px 170px; font-size:20px ">
        <tr>
            <td align="center">还没有订单</td>
        </tr>
    </table>

    {% endif %}
    <div class="modal fade" id="addcomment">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-title">
                    <h2 class="text-center">添加评论</h2>

                </div>
                <div class="modal-body">
                    <form class="form-group" id="form_comment" method="post" action="/user/save_comment/">
                        {% csrf_token %}
                        <div id="content">

                        </div>

                    </form>
                </div>

            </div>
        </div>

    </div>

</div>


{% endblock user_right %}

running_shopping/templates/usertest/user_center_site.html
{% extends 'base_user.html' %}
{% block meta %}
<meta charset="utf-8">

<meta http-equiv="X-UA-Compatible" content="IE=edge">

<meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock meta %}
{% block base_script %}
<link href="/static/css/bootstrap.min.css" rel="stylesheet">

<script src="/static/js/jquery-1.11.0.min.js"></script>

<script src="/static/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/static/js/jquery-1.8.3.js"></script>
<script type="text/javascript" src="/static/js/jquery.cookie.js"></script>
<script type="text/javascript" src="/static/js/site.js"></script>


{% endblock base_script %}
{% block user_left %}

<div class="left_menu_con clearfix">
    <h3>用户中心</h3>
    <ul>
        <li><a href="{% url 'usertest:info' %}">· 个人信息</a></li>
        <li><a href="{% url 'usertest:order' %}">· 全部订单</a></li>
        <li><a href="{% url 'usertest:site' %}" class="active">· 收货地址</a></li>
    </ul>
</div>
{% endblock user_left %}


{% block user_right %}

<div class="right_content clearfix">


    <h3 class="common_title2">收货地址</h3>
    <div class="">

        <a class="add_site" data-toggle="modal" data-target="#addsite">新增地址 </a>

    </div>
    <div class="addsite">
        <div class="site_con">
            <dl>
                <dt>默认地址：</dt>
                <dd>{{ caddress }} （{{cuseraddress.urecipients}} 收） <span>{{cuseraddress.uaddphone}}</span></dd>
            </dl>
            <div class="site_a">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a data-toggle="modal" data-target="#modifysite" onclick="modefysite({{ cuseraddress.pk }})"> 编辑地址</a>

            </div>


        </div>
    </div>
    {% for each in address_list %}

    <div class="addsite">
        <div class="site_con">
            <dl>
                <dt>地址：<em>{{ each.another_name }} </em></dt>
                <dd>{{each.uaddress}} （<em>{{each.urecipients}}</em> 收） <span>{{each.uaddphone}}</span></dd>


            </dl>
            <div class="site_a">
                <a href="" onclick="set_default({{ each.pk }})" class="set_default">设为默认 </a> &nbsp;&nbsp;&nbsp;&nbsp;
                <a data-toggle="modal" data-target="#modifysite" onclick="modefysite({{ each.pk }})"> 编辑地址</a>

            </div>


        </div>
    </div>
    {% endfor %}


    <div class="modal fade" id="addsite">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-title">
                    <h1 class="text-center">新增地址</h1>

                </div>
                <div class="modal-body">
                    <form class="form-group" method="post" action="../site_hander/">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>地址别名</label>
                            <input class="form-control" type="text" name="another_name" placeholder="请输入地址别名"/>
                        </div>
                        <div class="form-group">
                            <label>收件人</label>
                            <input class="form-control" type="text" name="urecipients" placeholder="请输入收件人姓名"/>
                        </div>
                        <div class="form-group">

                            <div class="address">
                                <label>地址 &nbsp; &nbsp; &nbsp; &nbsp;</label>
                                <select class="pro" name="pro_id">
                                    <option value="-1">请选择省份</option>
                                </select>

                            </div>

                        </div>
                        <div class="form-group">
                            <label>详细地址</label>
                            <input class="form-control" type="text" name="uaddress" placeholder="请输入收货地址"/>
                        </div>
                        <div class="form-group">
                            <label>邮编</label>
                            <input class="form-control" type="text" name="upostcode" placeholder="请输入邮政编码"/>
                        </div>
                        <div class="form-group">
                            <label>联系方式</label>
                            <input class="form-control" type="text" name="uaddphone" placeholder="请输入手机号"/>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-primary" type="submit">提交</button>
                            <button class="btn btn-danger" data-dismiss="modal">取消</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>


    <div class="modal fade" id="modifysite">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-title">
                    <h1 class="text-center">修改地址</h1>

                </div>
                <div class="modal-body">
                    <form class="form-group" method="post" action="../site_modify/">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>地址别名</label>
                            <input class="form-control" type="text" id="another_name" name="another_name"
                                   placeholder="请输入地址别名"/>
                        </div>
                        <div class="form-group">
                            <label>收件人</label>
                            <input class="form-control" type="text" id="urecipients" name="urecipients"
                                   placeholder="请输入收件人姓名"/>
                        </div>
                        <div class="form-group">

                            <div class="address">
                                <label>地址 &nbsp; &nbsp; &nbsp; &nbsp;</label>
                                <select class="pro" id="pro" name="pro_id">
                                    <option value="-1">请选择省份</option>
                                </select><select class="city" id="city" name="city_id">
                                <option value="-1">请选择市</option>
                            </select>
                                <select class="disc" id="disc" name="disc_id">
                                    <option value="-1">请选择区、县</option>
                                </select>


                            </div>

                        </div>

                        <div class="form-group">
                            <label>详细地址</label>
                            <input class="form-control" type="text" id="uaddress" name="uaddress"
                                   placeholder="请输入收货地址"/>
                        </div>
                        <div class="form-group">
                            <label>邮编</label>
                            <input class="form-control" type="text" id="upostcode" name="upostcode"
                                   placeholder="请输入邮政编码"/>
                        </div>
                        <div class="form-group">
                            <label>联系方式</label>
                            <input class="form-control" type="text" id="uaddphone" name="uaddphone"
                                   placeholder="请输入手机号"/>
                        </div>
                        <div class="text-right">
                            <button class="btn btn-primary" type="submit">提交</button>
                            <button class="btn btn-danger" data-dismiss="modal">取消</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>
</div>

{% endblock user_right %}