running_shopping/carttest/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views, view_order

urlpatterns = [
    # 购物车
    url(r'^$', views.cart, name='cart'),
    # 添加商品
    url(r'addcart(\d+)_(\d+)/$', views.addcart, name='addcart'),
    # 输出用户所以商品
    url(r'^item/$', views.item),
    # 增加或减少商品数量
    url(r'^alter(\d+)_(\d+)/$', views.alter),
    # blur 输入数据错误
    url(r'^error(\d+)/$', views.error),
    # 删除购物车数据
    url(r'^delete_item(\d+)/$', views.delete_item),
    # 获取用户购物车数量
    url(r'^goods_count/$', views.goods_count),

]

running_shopping/goodstest/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),  # 主页
    url(r'^list_([0-9]+)/$', views.listgoods, name='list'),  # 列表页
    url(r'^detail_([0-9]+)/$', views.detail, name='detail'),  # 商品详情页
    url(r'^search/$', views.MySearchView()),  # 商品搜索
    url(r'^addlike/$', views.addlike),
    url(r'^adddislike/$', views.adddislike),

]

running_shopping/running_shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('goodstest.urls', namespace='goodstest')),
    url(r'^user/', include('usertest.urls', namespace='usertest')),
    url(r'^cart/', include('carttest.urls', namespace='carttest')),
    url(r'^order/',include('ordertest.urls',namespace='ordertest'))
]

running_shopping/templates/search/search.html
{% extends 'base_goods.html' %}
{% load highlight %}


{% block goods_script %}

<script type="text/javascript" src="/static/js/jquery-1.8.3.js"></script>
<script type="text/javascript" src='/static/js/list.js'></script>

{% endblock goods_script %}
{% block user_body %}


<div class="breadcrumb">
    <a href="{% url 'goodstest:index' %}">全部分类</a>
    <span>></span>
    <a href="">{{ title }}</a>
</div>

<div class="main_wrap clearfix">
    <div class="l_wrap fl clearfix">
        <div class="new_goods">
            <h3>热门商品</h3>
            <ul>
                {% for item in latest_type %}
                <li>
                    <a href="/detail_{{ item.pk }}"><img src="/static/media/{{ item.gimage }}" title="{{ item.gtitle }}" ></a>
                    <h4><a href="/detail_{{ item.pk }}">{{ item.gtitle }}</a></h4>
                    <div class="prize">￥{{ item.gprice }}</div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    {% if query %}

    <div class="r_wrap fr clearfix">

        <div class="sort_bar">
            {% for item in sort_bar %}
            {% if rank == item.id %}
            <a href="?q={{ query }}&amp;rank={{ item.id }}" class="active">{{ item.name }} </a>
            {% else %}
            <a href="?q={{ query }}&amp;rank={{ item.id }}">{{ item.name }}</a>
            {% endif %}
            {% endfor %}
        </div>


        <ul class="goods_type_list clearfix">

            {% for item in page.object_list %}



            <li>
                <a href="/detail_{{ item.pk }}"><img src="/static/media/{{ item.gimage }}" title="{{ item.gtitle }}" ></a>
                <h4><a href="/detail_{{ item.object.pk }}">{% highlight item.gtitle with query %}</a></h4>
                <div class="operate">
                    <span class="prize">￥{{ item.gprice }}</span>
                    <span class="unit">{{ item.gprice }}/{{ item.gweight }}</span>
                    <a  href="{% url 'carttest:addcart' item.pk 1 %}" class="add_goods" title="加入购物车"></a>
                </div>
            </li>

            {% endfor %}

        </ul>

        <div class="pagenation">
            {% if page.has_previous %}
            <a href="?q={{ query }}&amp;page={{ page.previous_page_number }}">上一页</a>
            {% else %}
            <a href="#" class="active2">上一页</a>
            {% endif %}


            {% if paginator.num_pages < 7 %}

                {% for index in paginator.page_range %}
                {% if index == page.number %}
                <a href="#" class="active">{{ index }}</a>
                {% else %}
                <a href="?q={{ query }}&amp;page={{ index }}&amp;rank={{ rank }}">{{ index }}</a>
                {% endif %}
                {% endfor %}
            {% else %}

                {% if page.number < 6 %}
                    {% for index in range_page %}
                        {% if index == page.number %}
                        <a href="#" class="active">{{ index }}</a>
                        {% else %}
                        <a href="?q={{ query }}&amp;page={{ index }}&amp;rank={{ rank }}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}
                    <a href="#" class="active2">...</a>
                    <a href="?q={{ query }}&amp;page={{ paginator.num_pages }}&amp;rank={{ rank }}">{{ paginator.num_pages }}</a>
                {% else%}
                    {% if page.number < pagenum %}

                        <a href="?q={{ query }}&amp;page=1">1</a>
                        <a href="?q={{ query }}&amp;page=2">2</a>
                        <a href="#" class="active2">...</a>
                        {% for index in range_page2 %}
                                {% if index == page.number %}
                                <a href="#" class="active">{{ index }}</a>
                                {% else %}
                                <a href="?q={{ query }}&amp;page={{ index }}&amp;rank={{ rank }}">{{ index }}</a>
                                {% endif %}
                        {% endfor %}
                        <a href="#" class="active">...</a>
                        <a href="?q={{ query }}&amp;page={{ paginator.num_pages }}&amp;rank={{ rank }}">{{ paginator.num_pages }}</a>

                    {% else %}
                        <a href="?q={{ query }}&amp;page=1&amp;rank={{ rank }}">1</a>
                        <a href="?q={{ query }}&amp;page=2&amp;rank={{ rank }}">2</a>
                        <a href="#" class="active2">...</a>

                        {% for index in range_page2 %}
                                {% if index == page.number %}
                                <a href="#" class="active">{{ index }}</a>
                                {% else %}
                                <a href="?q={{ query }}&amp;page={{ index }}&amp;rank={{ rank }}">{{ index }}</a>
                                {% endif %}
                        {% endfor %}

                    {% endif %}




                {% endif %}

            {% endif %}


            {% if page.has_next %}
            <a href="?q={{ query }}&amp;page={{ page.next_page_number }}&amp;rank={{ rank }}">下一页</a>
            {% else %}
            <a href="#" class="active2">下一页</a>
            {% endif %}
        </div>
    </div>

    {% endif %}
</div>


{% endblock user_body %} %}