running_shopping/carttest/urls.py
# -*- coding:utf-8 -*-

from django.conf.urls import url
from . import views, view_order

urlpatterns = [
    # 购物车
    url(r'^$', views.cart, name='cart'),
    # 添加商品
    url(r'addcart(\d+)_(\d+)/$', views.addcart, name='addcart'),
    # 输出用户所以商品
    url(r'^item/$', views.item),
    # 增加或减少商品数量
    url(r'^alter(\d+)_(\d+)/$', views.alter),
    # blur 输入数据错误
    url(r'^error(\d+)/$', views.error),
    # 删除购物车数据
    url(r'^delete_item(\d+)/$', views.delete_item),
    # 获取用户购物车数量
    url(r'^goods_count/$', views.goods_count),

]

running_shopping/ordertest/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from . import views
urlpatterns=[
    url(r'^$', views.place_order, name='place_order'),#提交订单
    url(r'^order_hander/$',views.order_hander),#订单处理
    url(r'^alter_site/$',views.alter_site),#改变收货地址
    url(r'^detail_order/$',views.detail_order)#订单详情
]

running_shopping/running_shopping/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('goodstest.urls', namespace='goodstest')),
    url(r'^user/', include('usertest.urls', namespace='usertest')),
    url(r'^cart/', include('carttest.urls', namespace='carttest')),
    url(r'^order/',include('ordertest.urls',namespace='ordertest'))
]

running_shopping/carttest/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


# 购物车
class CartInfo(models.Model):
    cuser = models.ForeignKey('usertest.UserInfo')  # 用户
    cgoods = models.ForeignKey('goodstest.GoodsInfo')  # 购物车商品
    count = models.IntegerField()  # 商品数量

    def __str__(self):
        return self.cgoods.gtitle.encode('utf-8')

    class Meta():
        db_table = 'cartinfo'

running_shopping/carttest/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from models import CartInfo
from usertest.user_decorate import login_fun


# 添加装饰器，若用户没有登录，跳转到登录页面
@login_fun
def cart(request):
    # 从session信息中取出用户id
    pid = request.session.get('pid')
    carts = CartInfo.objects.filter(cuser_id=pid).order_by('-pk')
    # print '8888888888888888->',len(carts)
    context = {'title': '购物车', 'carts': carts, 'len': len(carts)}
    return render(request, 'carttest/cart.html', context)


# 添加商品
@login_fun
def addcart(request, gid, count):
    if request.session.has_key('pid'):
        gid = int(gid)
        count = int(count)
        # print '================gid count',gid,count
        pid = request.session.get('pid')
        # 查看购物车中是否有同样的商品，
        # 若有，改变购物车商品数量，
        # 没有则创建
        carts = CartInfo.objects.filter(cuser_id=pid, cgoods_id=gid)
        if carts:
            cart = carts[0]
            cart.count += count
        else:
            cart = CartInfo()
            cart.cuser_id = pid
            cart.cgoods_id = gid
            cart.count = count
        cart.save()  # 保存信息
        # 判断请求类型，如是在商品详情页（detail）添加，页面不跳转，
        # 如是在其他页面，页面跳转到购物车页面（cart）
        if request.is_ajax():
            return JsonResponse({'islogin': 1})
        else:
            return HttpResponseRedirect('/cart')
    else:
        return JsonResponse({'islogin': 0})


# 统计用户购物车商品，存到JsonResponse 中
def item(request):
    pid = request.session.get('pid')
    carts = CartInfo.objects.filter(cuser_id=pid)
    list = []
    for cart in carts:
        list.append(cart.pk)

    return JsonResponse({'data': list})


# 购物车商品数量改变，修改数据库信息
def alter(request, id, num):
    id = int(id)
    num = int(num)
    cart = CartInfo.objects.get(pk=id)
    try:
        count1 = cart.count
        cart.count = num

        cart.save()
        data = {'count': 0}
    except Exception as e:
        data = {'count': count1}
    return JsonResponse(data)


# blur 输入数据错误，JsonResponse 保存之前商品数量
def error(request, id):
    count = CartInfo.objects.get(pk=id).count

    return JsonResponse({'count': count})


# 删除购物车信息
def delete_item(request, id):
    id = int(id)
    try:
        print 'begin'
        cart = CartInfo.objects.get(pk=id)
        print cart.pk
        cart.delete()
        print 'delete'
        content = {'flag': 1}
    except Exception as e:
        content = {'flag': 0}

    return JsonResponse(content)


# 获取用户购物车数量
def goods_count(request):
    pid = request.session.get('pid')
    carts = CartInfo.objects.filter(cuser_id=pid)
    return JsonResponse({'count': len(carts)})

running_shopping/templates/carttest/cart.html
{% extends 'base_user.html' %}
{% block base_script %}

<script type="text/javascript" src='/static/js/cart.js'></script>
{% endblock base_script %}
{% block user_body %}


<div class="total_count">全部商品<em>{{ len }}</em>件</div>
<ul class="cart_list_th clearfix">
    <li class="col01">商品名称</li>
    <li class="col02">商品单位</li>
    <li class="col03">商品价格</li>
    <li class="col04">数量</li>
    <li class="col05">小计</li>
    <li class="col06">操作</li>
</ul>
{% for cart in carts %}

<ul class="cart_list_td clearfix" >


    <li class="col01"><input type="checkbox" id="check{{ cart.pk }}" name="" checked></li>
    <li class="col02"><img src="/static/media/{{ cart.cgoods.gimage }}"></li>
    <li class="col03">{{ cart.cgoods.gtitle }}<br><em>{{ cart.cgoods.gprice }}元/{{ cart.cgoods.gweight }}</em></li>
    <li class="col04">{{ cart.cgoods.gweight }}</li>
    <li class="col05" id='price{{ cart.pk }}'><em>{{ cart.cgoods.gprice }}</em>元</li>
    <li class="col06">
        <div class="num_add" >
            <a href="javascript:add({{ cart.pk }});" class="add fl">+</a>
            <input type="text" id='{{ cart.pk }}' class="num_show fl" value="{{ cart.count }}">
            <a href="javascript:reduce({{ cart.pk }});" class="minus fl">-</a>
        </div>
    </li>
    <li class="col07" id='total{{ cart.pk }}'></li>
    <li class="col08"><a  onclick="delete_item({{ cart.pk }});">删除</a></li>
</ul>
{% endfor %}




<ul class="settlements">
    <li class="col01"><input type="checkbox" name="" checked="" id='checkall' ></li>
    <li class="col02">全选</li>
    <li class="col03">合计(不含运费)：<span>¥</span><em>42.60</em><br>共计<b>2</b>件商品</li>
    <li class="col04"><a href="{% url 'ordertest:place_order' %}" >去结算</a></li>
</ul>

{% endblock user_body %}